---

pf_rule: |
  block return
  # pass SSH to me
  pass quick proto tcp from any to self port ssh
  # pass lo
  pass quick on lo all
  # pass all ICMPs
  pass quick inet  proto icmp  from any to self
  pass quick inet6 proto icmp6 from any to self
  # pass all packets from me
  pass quick from self to any
  # pass DHCP
  pass quick proto udp from any to any port { bootpc, bootps }
  # pass HTTP(S)
  pass quick proto {tcp, udp} from any to self port { http, https }

httpd_openbsd_log_directories:
  - path: /var/log/www
    owner: root
    group: www
    mode: 0755
    state: present
httpd_openbsd_config: |
  prefork 1
  chroot "/var/www"
  logdir "{{ httpd_openbsd_log_directories[0]['path'] }}"

  # defaults to 410 Gone
  server "default" {
    listen on "*" port 80
    block return 410
  }

  server "demo.i.trombik.org" {
    listen on "*" port 80
    root "htdocs/sites/demo/_site"
  }
  types {
    include "/usr/share/misc/mime.types"
  }

jekyll_user: trombik
jekyll_bundler_bin: "bundle{{ language_ruby_version.short }}"
jekyll_repositories:
  - name: demo
    module: git
    config:
      repo: https://github.com/trombik/jekyll-site-info.i.mkrsgh.org
      dest: /var/www/htdocs/sites/demo
      version: devel
      force: yes
      update: yes
      state: latest
    bundler:
      deployment_mode: yes
      user_install: yes
      extra_args: --path $HOME/.gem
