---
os: linux
dist: bionic
language: python
python: "3.6"

# Install ansible
addons:
  apt:
    update: true
    packages:
      - python-pip
      - curl
      - bridge-utils
      - dnsmasq-base
      - ebtables
      - libvirt-bin
      - libvirt-dev
      - qemu-kvm
      - qemu-utils
      - ruby-dev
      - jq
cache:
  directories:
    - $HOME/.rvm/
    - $HOME/.bundler/
    - $HOME/.cache/pip/
    - $HOME/.vagrant.d/boxes/
  pip: true

before_install:
  # XXX update RubyGem to fix build in Travis CI. when ruby 2.6.3 or later is
  # available in travis environment, this can be removed.
  # see details at:
  # https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
  - yes | gem update --system --force
  - gem install bundler
  - wget https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  - sudo dpkg -i vagrant_2.2.9_x86_64.deb
  - vagrant --version

  # for libvirt
  - vagrant plugin install vagrant-libvirt
  - sudo chmod go+rw /var/run/libvirt/libvirt-sock

  # for virtualbox
  - sudo apt-get install "linux-headers-`uname -r`"
  - wget -q https://github.com/trombik/ansible-role-sensu_go_backend/releases/download/1.4.0/oracle_vbox_2016.asc -O - | sudo apt-key add -
  - sudo add-apt-repository -y "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian `lsb_release -cs` contrib"
  - sudo apt-get update
  - sudo apt-get install virtualbox-6.1

install:
  # Install ansible
  - pip install ansible yamllint molecule docker

  # Check versions
  - ansible --version
  - molecule --version

script:
  # Download depended roles
  - if [ -f requirements.yml ]; then ansible-galaxy install -r requirements.yml -p extra_roles; fi
  - if [ -f requirements.yml ]; then ansible-galaxy collection install -r requirements.yml -p collections; fi

  # export PATH
  - export PATH="${PATH}:`rvm gemdir`/bin"

  # bundle up because rubocop is installed via Gemfile
  - bundle install --path ${HOME}/.bundler

  # run rubocop
  - bundle exec rubocop

  # run yamllint
  - yamllint -c .yamllint.yml .

  # run the test
  - bundle exec rake test
