---
- name: trombik.localtime
  version: 1.1.0
- name: trombik.vim
  version: 1.1.2
- name: trombik.zsh
  version: 1.1.1
- name: trombik.hostname
  version: 1.0.1
- name: trombik.hosts
  version: 2.0.1
- name: trombik.git
  version: 1.1.2
- name: trombik.pf
  version: 1.1.0
- name: trombik.httpd-openbsd
